CodingZeal/redwood-template-app

- README.md
- package.json
- prettier.config.js
- web/config/postcss.config.js
- web/config/tailwind.config.js
- web/package.json
- web/src/index.css
- yarn.lock
RESOLVE #9
Add TailwindCSS to code base
> 🔧 Add tailwind

- .gitignore
- .vscode/extensions.json
- .vscode/launch.json
RESOLVE #10 
Add configuration for development in VS Code 
> 🔧 Add vs code configuration

- .github/workflows/playwright.yml
- .prettierignore
- Ignore some files.
- Name and change e2e workflow run only for PR's (can still be run manually whenever)
> 🧹 - make prettier ignore & adjust playwright workflow

- web/src/components/ZealLogo/index.tsx
- web/src/pages/HomePage/HomePage.tsx
Chore #54 ZealLogo Component Update
ZealLogo Component  and HomePage Update
Remove index.tsx, connect ZealLogo component to HomePage.tsx
ZealLogo component, HomePage
> ZealLogo Component Update

- web/src/pages/ForbiddenPage/ForbiddenPage.tsx
Resolves #55 Forbidden Page Sync
Forbidden Page update UI to sync with similar pages
Update Forbidden Page to sync with Not Found and Fatal Error Page structure
Forbidden Page
> 🧹 Forbidden Page Update

- web/src/components/Admin/Role/EditRoleCell/EditRoleCell.tsx
- web/src/components/Admin/Role/RoleCell/RoleCell.tsx
- web/src/components/Admin/Team/EditTeamCell/EditTeamCell.tsx
- web/src/components/Admin/Team/TeamCell/TeamCell.tsx
- web/src/components/Admin/User/EditUserCell/EditUserCell.tsx
- web/src/components/Admin/User/UserCell/UserCell.tsx
- web/src/pages/Admin/Role/EditRolePage/EditRolePage.tsx
- web/src/pages/Admin/Role/NewRolePage/NewRolePage.tsx
- web/src/pages/Admin/Role/RolePage/RolePage.tsx
- web/src/pages/Admin/Role/RolesPage/RolesPage.tsx
- web/src/pages/Admin/Team/EditTeamPage/EditTeamPage.tsx
- web/src/pages/Admin/Team/NewTeamPage/NewTeamPage.tsx
- web/src/pages/Admin/Team/TeamPage/TeamPage.tsx
- web/src/pages/Admin/Team/TeamsPage/TeamsPage.tsx
- web/src/pages/Admin/User/EditUserPage/EditUserPage.tsx
- web/src/pages/Admin/User/NewUserPage/NewUserPage.tsx
- web/src/pages/Admin/User/UserPage/UserPage.tsx
- web/src/pages/Admin/User/UsersPage/UsersPage.tsx
- web/src/pages/FatalErrorPage/FatalErrorPage.tsx
- web/src/pages/ForbiddenPage/ForbiddenPage.tsx
- web/src/pages/NotFoundPage/NotFoundPage.tsx
> Add html titles

- api/src/services/users/users.ts
User Service remove duplicate team/role creation/update
Fix #51 
Moved user role/team association logic into a separate method that can be called from create or update
User Admin
No changes needed
> ♻️  DRY up createUser and updateUser

- api/src/graphql/profile.sdl.ts
- api/src/lib/auth.ts
- api/src/services/profile/profile.scenarios.ts
- api/src/services/profile/profile.test.ts
- api/src/services/profile/profile.ts
- web/src/Routes.tsx
- web/src/components/Navigation/Navigation.tsx
- web/src/components/Profile/Profile.stories.tsx
- web/src/components/Profile/Profile.test.tsx
- web/src/components/Profile/Profile.tsx
- web/src/components/ProfileCell.tsx
- web/src/components/ProfileCell/ProfileCell.mock.ts
- web/src/components/ProfileCell/ProfileCell.stories.tsx
- web/src/components/ProfileCell/ProfileCell.test.tsx
- web/src/components/ProfileCell/ProfileCell.tsx
- web/src/pages/ProfilePage/ProfilePage.stories.tsx
- web/src/pages/ProfilePage/ProfilePage.test.tsx
- web/src/pages/ProfilePage/ProfilePage.tsx
Fix #56 Feature profile page
Profile Page for current user logged in, ability to edit profile. 
Profile add in GraphQL and Services. Profile Page add with Profile component and cell. Current user has profile page in navigation. Current user has ability to edit profile and save. 
Profile GraphQL, Profile Services, Profile Page, Profile Component and Cell
Profile Component test, Profile Cell Test, Profile Service Test
> ✨ Feature/56 profile page

- web/src/components/Navigation/index.tsx
- web/src/layouts/MainLayout.tsx
Remove Navigation index.tsx
Fix #63 
Follow Redwoodjs patterns for exporting components
Navigation
> 🧹 Remove Navigation/index.tsx

- api/db/schema.prisma
- api/package.json
- api/server.config.js
- api/src/functions/graphql.ts
- package.json
- web/package.json
- yarn.lock
Resolves [#72](https://github.com/CodingZeal/redwood-template-app/issues/72#issue-1374424819) 
Redwood upgrade to 3
> Issue: #72 Upgrade redwood to 3

- web/src/components/Admin/Role/EditRoleCell/EditRoleCell.mock.ts
- web/src/components/Admin/Role/EditRoleCell/EditRoleCell.test.tsx
- web/src/components/Admin/Role/NewRole/NewRole.test.tsx
- web/src/components/Admin/Role/Role/Role.test.tsx
- web/src/components/Admin/Role/RoleCell/RoleCell.mock.ts
- web/src/components/Admin/Role/RoleCell/RoleCell.test.tsx
- web/src/components/Admin/Role/RoleForm/RoleForm.test.tsx
- web/src/components/Admin/Role/Roles/Roles.test.tsx
- web/src/components/Admin/Role/RolesCell/RolesCell.mock.ts
- web/src/components/Admin/Role/RolesCell/RolesCell.test.tsx
- web/src/pages/Admin/Role/EditRolePage/EditRolePage.test.tsx
- web/src/pages/Admin/Role/NewRolePage/NewRolePage.test.tsx
- web/src/pages/Admin/Role/RolePage/RolePage.test.tsx
- web/src/pages/Admin/Role/RolesPage/RolesPage.test.tsx
Fix #67 Chore/67 role tests
Admin Role feature tests in components and pages
Feature tests for admin-roles components, cells, and pages testing rendering and functionality. 
Admin Roles components and pages
Admin Roles Component, Cell, and Page tests for features. 
> 🧹 Chore/67 role tests

- web/package.json
- web/src/pages/ResetPasswordPage/ResetPasswordPage.test.tsx
- web/src/pages/ResetPasswordPage/ResetPasswordPage.tsx
- yarn.lock
Fix #67 Chore/reset password test
Test for Reset-Password Page
Test made for testing functionality on reset-password page
Reset-Password Test
Test functionality to reset a user's password
> 🧹 Chore/reset password test

- .prettierignore
Fix #59
Ignore linty things...
> 🧹 Chore/59 more lint ignores

- api/package.json
- package.json
- web/package.json
- yarn.lock
Upgrade RedwoodJS to 3.2.0
RedwoodJS core
> ⬆️ Update to RedwoodJS 3.2.0

- README.md
Fix #83 #60 #82 #81 #69 
Document features
Readme documentation
> 📝 Document all the features

- web/tests/admin-roles.spec.ts
- web/tests/admin-teams.spec.ts
Fix #68 
End to end feature testing as an admin
Feature testing for crud operations as an admin for teams and roles
Playwright tests for admin-teams and admin-roles. 
End-to-end feature testing for admin going through CRUD operations with teams and roles. 
#131 
> 🧹 Chore/68 admin e2e

- api/package.json
- package.json
- web/package.json
- yarn.lock
Upgrade dependencies 
Redwood to 3.5
Prettier
Playwright
Tailwind
Add any related pull requests
> upgrade deps; upgrade to redwood 3.5

- api/src/functions/auth.ts
- web/playwright.config.ts
Fix issue with Safari Cookie issue with Secure header
Add any related pull requests
> fix safari cookie issue with secure header

- api/src/services/profile/profile.test.ts
- api/src/services/roles/roles.test.ts
- api/src/services/teams/teams.test.ts
- api/src/services/users/users.test.ts
Fix #117 
Intermittent test failure on the service tests. 
Adjust test regarding date and time tests to be greater/lesser than or equal to the time created or updated 
Adjust test regarding deleting teams, added await for the promise of rejecting. 
Api Service tests, users/teams/roles/profile
Api Service users/teams/roles/profile test updated with await for the promise present. 
> 🐛 Bug/intermittent failure

- .github/workflows/api.yml
- api/package.json
- package.json
- web/package.json
- web/src/components/Navigation/Navigation.tsx
- yarn.lock
- Fix broken OpenSSL API dependency in CI
- Fix Nested LI's... bad DOM. bad.
- Bump upgradable packages.
> Updates, Upgrades, CI System images.. OH MY!
